package raf.dsw.message;

public enum PossibleErrors {
    NODE_CANNOT_BE_DELETED, CANT_ADD_CHILD, NAME_ALREADY_EXISTS, NO_NODE_SELECTED_FOR_ADD_CHILD,
    PP_ACTION_FOR_NOTPP, AUTHOR_ACTION_FOR_NOT_PROJECT,
    EXISTS_SAME_NAME_COMPONENT, NODE_NOT_SELECTED, NAME_CANNOT_BE_EMPTY, CANNOT_DELETE_PROJECTEXPLORER;
}
