package raf.dsw.message;

public enum PossibleErrors {
    NODE_CANNOT_BE_DELETED, CANT_ADD_CHILD, NAME_ALREADY_EXISTS, NO_NODE_SELECTED_FOR_ADD_CHILD,
    TYPE_OF_IC_NOT_SELECTED, TYPE_OF_CON_NOT_SELECTED, NO_NAME_FOR_DIAGRAM_ELEMENT,
    PP_ACTION_FOR_NOTPP, AUTHOR_ACTION_FOR_NOT_PROJECT, WRONG_SELECTION_FOR_DUPLICATE,
    EXISTS_SAME_NAME_COMPONENT, NODE_NOT_SELECTED, NAME_CANNOT_BE_EMPTY, CANNOT_DELETE_PROJECTEXPLORER;
}
